// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SimpleFlow.proto

#include "SimpleFlow.pb.h"
#include "SimpleFlow.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace simple_flow_offload {

static const char* SimpleFlowOffload_method_names[] = {
  "/simple_flow_offload.SimpleFlowOffload/CreateFlow",
};

std::unique_ptr< SimpleFlowOffload::Stub> SimpleFlowOffload::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SimpleFlowOffload::Stub> stub(new SimpleFlowOffload::Stub(channel, options));
  return stub;
}

SimpleFlowOffload::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateFlow_(SimpleFlowOffload_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SimpleFlowOffload::Stub::CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::simple_flow_offload::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateFlow_, context, request, response);
}

void SimpleFlowOffload::Stub::async::CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFlow_, context, request, response, std::move(f));
}

void SimpleFlowOffload::Stub::async::CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFlow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>* SimpleFlowOffload::Stub::PrepareAsyncCreateFlowRaw(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::simple_flow_offload::Reply, ::simple_flow_offload::FlowRule, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateFlow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>* SimpleFlowOffload::Stub::AsyncCreateFlowRaw(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateFlowRaw(context, request, cq);
  result->StartCall();
  return result;
}

SimpleFlowOffload::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SimpleFlowOffload_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SimpleFlowOffload::Service, ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SimpleFlowOffload::Service* service,
             ::grpc::ServerContext* ctx,
             const ::simple_flow_offload::FlowRule* req,
             ::simple_flow_offload::Reply* resp) {
               return service->CreateFlow(ctx, req, resp);
             }, this)));
}

SimpleFlowOffload::Service::~Service() {
}

::grpc::Status SimpleFlowOffload::Service::CreateFlow(::grpc::ServerContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace simple_flow_offload

