// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SimpleFlow.proto
#ifndef GRPC_SimpleFlow_2eproto__INCLUDED
#define GRPC_SimpleFlow_2eproto__INCLUDED

#include "SimpleFlow.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace simple_flow_offload {

class SimpleFlowOffload final {
 public:
  static constexpr char const* service_full_name() {
    return "simple_flow_offload.SimpleFlowOffload";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::simple_flow_offload::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::simple_flow_offload::Reply>> AsyncCreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::simple_flow_offload::Reply>>(AsyncCreateFlowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::simple_flow_offload::Reply>> PrepareAsyncCreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::simple_flow_offload::Reply>>(PrepareAsyncCreateFlowRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::simple_flow_offload::Reply>* AsyncCreateFlowRaw(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::simple_flow_offload::Reply>* PrepareAsyncCreateFlowRaw(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::simple_flow_offload::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>> AsyncCreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>>(AsyncCreateFlowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>> PrepareAsyncCreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>>(PrepareAsyncCreateFlowRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response, std::function<void(::grpc::Status)>) override;
      void CreateFlow(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>* AsyncCreateFlowRaw(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::simple_flow_offload::Reply>* PrepareAsyncCreateFlowRaw(::grpc::ClientContext* context, const ::simple_flow_offload::FlowRule& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateFlow_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateFlow(::grpc::ServerContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateFlow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateFlow() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateFlow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFlow(::grpc::ServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFlow(::grpc::ServerContext* context, ::simple_flow_offload::FlowRule* request, ::grpc::ServerAsyncResponseWriter< ::simple_flow_offload::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateFlow<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateFlow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateFlow() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::simple_flow_offload::FlowRule* request, ::simple_flow_offload::Reply* response) { return this->CreateFlow(context, request, response); }));}
    void SetMessageAllocatorFor_CreateFlow(
        ::grpc::MessageAllocator< ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateFlow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFlow(::grpc::ServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateFlow(
      ::grpc::CallbackServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateFlow<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateFlow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateFlow() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateFlow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFlow(::grpc::ServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateFlow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateFlow() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateFlow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFlow(::grpc::ServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFlow(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateFlow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateFlow() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateFlow(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateFlow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFlow(::grpc::ServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateFlow(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateFlow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateFlow() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::simple_flow_offload::FlowRule, ::simple_flow_offload::Reply>* streamer) {
                       return this->StreamedCreateFlow(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateFlow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateFlow(::grpc::ServerContext* /*context*/, const ::simple_flow_offload::FlowRule* /*request*/, ::simple_flow_offload::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateFlow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::simple_flow_offload::FlowRule,::simple_flow_offload::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateFlow<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateFlow<Service > StreamedService;
};

}  // namespace simple_flow_offload


#endif  // GRPC_SimpleFlow_2eproto__INCLUDED
